services:
  db:
    build: ./docker/pql
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 1g
    volumes:
      - ./docker/pql/schema.sh:/docker-entrypoint-initdb.d/schema.sh:ro
      - pgdata:/var/lib/postgresql/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: