from sentence_transformers import SentenceTransformer
import torch

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2', device='cuda')

sentences = [
    # physics paper
    "Knowledge of fundamental traffic flow characteristics of traffic simulation models is an essential requirement when using these models for the planning, design, and operation of transportation systems. In this paper we discuss the following: a description of how features relevant to traffic flow are currently under implementation in the TRANSIMS microsimulation, a proposition for standardized traffic flow tests for traffic simulation models, and the results of these tests for two different versions of the TRANSIMS microsimulation.",
    # physics paper 2
    "This paper reports experiences with iterated traffic microsimulations in the context of a Dallas study. ``Iterated microsimulations'' here means that the information generated by a microsimulation is fed back into the route planner so that the simulated individuals can adjust their routes to circumvent congestion. This paper gives an overview over what has been done in the Dallas context to better understand the relaxation process, and how to judge the robustness of the results.",
    # general robotics control paper
    "This paper initiates the use of vector fields to design, optimize, and implement reactive schedules for safe cooperative robot patterns on planar graphs. We consider Automated Guided Vehicles (AGV's) operating upon a predefined network of pathways. In contrast to the case of locally Euclidean configuration spaces, regularization of collisions is no longer a local procedure, and issues concerning the global topology of configuration spaces must be addressed. The focus of the present inquiry is the achievement of safe, efficient, cooperative patterns in the simplest nontrivial example (a pair of robots on a Y-network) by means of a state-event heirarchical controller.",
    # specific robotics slam paper
    "FastSLAM is a framework for simultaneous localization using a Rao-Blackwellized particle filter. In FastSLAM, particle filter is used for the mobile robot pose (position and orientation) estimation, and an Extended Kalman Filter (EKF) is used for the feature location's estimation. However, FastSLAM degenerates over time. This degeneracy is due to the fact that a particle set estimating the pose of the robot loses its diversity. One of the main reasons for loosing particle diversity in FastSLAM is sample impoverishment. It occurs when likelihood lies in the tail of the proposal distribution. In this case, most of particle weights are insignificant. Another problem of FastSLAM relates to the design of an extended Kalman filter for landmark position's estimation. The performance of the EKF and the quality of the estimation depends heavily on correct a priori knowledge of the process and measurement noise covariance matrices (Q and R) that are in most applications unknown. On the other hand, an incorrect a priori knowledge of Q and R may seriously degrade the performance of the Kalman filter. This paper presents a Neuro-Fuzzy Multi Swarm FastSLAM Framework. In our proposed method, a Neuro-Fuzzy extended kalman filter for landmark feature estimation, and a particle filter based on particle swarm optimization are presented to overcome the impoverishment of FastSLAM. Experimental results demonstrate the effectiveness of the proposed algorithm.",
    # specific robotics slam paper
    "We present a novel spectral learning algorithm for simultaneous localization and mapping (SLAM) from range data with known correspondences. This algorithm is an instance of a general spectral system identification framework, from which it inherits several desirable properties, including statistical consistency and no local optima. Compared with popular batch optimization or multiple-hypothesis tracking (MHT) methods for range-only SLAM, our spectral approach offers guaranteed low computational requirements and good tracking performance. Compared with popular extended Kalman filter (EKF) or extended information filter (EIF) approaches, and many MHT ones, our approach does not need to linearize a transition or measurement model; such linearizations can cause severe errors in EKFs and EIFs, and to a lesser extent MHT, particularly for the highly non-Gaussian posteriors encountered in range-only SLAM. We provide a theoretical analysis of our method, including finite-sample error bounds. Finally, we demonstrate on a real-world robotic SLAM problem that our algorithm is not only theoretically justified, but works well in practice: in a comparison of multiple methods, the lowest errors come from a combination of our algorithm with batch optimization, but our method alone produces nearly as good a result at far lower computational cost"
]

embeddings = model.encode(sentences)
print(embeddings.shape)
# [5, 768]

similarities = model.similarity(embeddings, embeddings)
torch.set_printoptions(sci_mode=False)
print(similarities)
# tensor([[ 1.0000,  0.7357,  0.1594,  0.0607, -0.0134],
#         [ 0.7357,  1.0000,  0.2944,  0.0642,  0.0789],
#         [ 0.1594,  0.2944,  1.0000,  0.1098,  0.1778],
#         [ 0.0607,  0.0642,  0.1098,  1.0000,  0.4557],
#         [-0.0134,  0.0789,  0.1778,  0.4557,  1.0000]])

# higher similarity between robotics papers. Even higher similarity between robotics SLAM specific papers
